version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    ports:
      - '3000:3000'
    environment:
      - PG_DB=node_db
      - PG_USER=reza.sadr
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=node_db
      - POSTGRES_USER=reza.sadr
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
